// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STRACT.Data.Identity;

namespace STRACT.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PDC")
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ActionItemLineOfProduct", b =>
                {
                    b.Property<int>("ActionItemsActionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesOfProductsLineOfProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionItemsActionItemId", "LinesOfProductsLineOfProductId");

                    b.HasIndex("LinesOfProductsLineOfProductId");

                    b.ToTable("ActionItemLineOfProduct");
                });

            modelBuilder.Entity("ActivityFunctionalRole", b =>
                {
                    b.Property<int>("ActivitiesActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FunctionalRolesFunctionalRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivitiesActivityId", "FunctionalRolesFunctionalRoleId");

                    b.HasIndex("FunctionalRolesFunctionalRoleId");

                    b.ToTable("ActivityFunctionalRole");
                });

            modelBuilder.Entity("ActivityOrganizationalRole", b =>
                {
                    b.Property<int>("ActivitiesActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizationalRolesOrganizationalRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivitiesActivityId", "OrganizationalRolesOrganizationalRoleId");

                    b.HasIndex("OrganizationalRolesOrganizationalRoleId");

                    b.ToTable("ActivityOrganizationalRole");
                });

            modelBuilder.Entity("ActivitySkill", b =>
                {
                    b.Property<int>("ActivitiesActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsSkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivitiesActivityId", "SkillsSkillId");

                    b.HasIndex("SkillsSkillId");

                    b.ToTable("ActivitySkill");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificationLineId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfAudit")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuditId");

                    b.HasIndex("CertificationLineId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CertificationLineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("CertificateId");

                    b.HasIndex("CertificationLineId");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificateProductLine", b =>
                {
                    b.Property<int>("ProductLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineOfProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductLineId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("LineOfProductId");

                    b.ToTable("CertificateProductLines");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificationInActionItem", b =>
                {
                    b.Property<int>("CertificationLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificationLineId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("CertificationLineId");

                    b.HasIndex("ActionItemId");

                    b.HasIndex("CertificationLineId1");

                    b.ToTable("CertificationInActionItems");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificationLine", b =>
                {
                    b.Property<int>("CertificationLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FactoryAudit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationLineId");

                    b.HasIndex("EntityId");

                    b.ToTable("CertificationLine");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.ContactPerson", b =>
                {
                    b.Property<int>("ContactPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMainContact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactPersonId");

                    b.HasIndex("EntityId");

                    b.ToTable("ContactPerson");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramLine", b =>
                {
                    b.Property<int>("ChronogramLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChronogramRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChronogramTextId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PercentOfConclusion")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.HasKey("ChronogramLineId");

                    b.HasIndex("ChronogramRevisionId");

                    b.HasIndex("ChronogramTextId");

                    b.ToTable("ChronogramLine");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramRevision", b =>
                {
                    b.Property<int>("ChronogramRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsibleUserInTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RevisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChronogramRevisionId");

                    b.HasIndex("ProjectItemId");

                    b.HasIndex("ResponsibleUserInTeamId");

                    b.ToTable("ChronogramRevision");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramText", b =>
                {
                    b.Property<int>("ChronogramTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Milestone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Repeatable")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChronogramTextId");

                    b.ToTable("ChronogramText");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Commission", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CommissionId");

                    b.ToTable("Commission");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.CommissionForProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Advantages")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proposal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportDocuments")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("CommissionId");

                    b.ToTable("CommissionForProject");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Decision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommissionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfDecision")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Minutes")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("DecisionId");

                    b.HasIndex("CommissionId");

                    b.HasIndex("StatusId");

                    b.ToTable("Decision");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Proposal", b =>
                {
                    b.Property<int>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommissionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponsibleUserInTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProposalId");

                    b.HasIndex("CommissionId");

                    b.HasIndex("ResponsibleUserInTeamId");

                    b.ToTable("Proposal");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.ProposalStatus", b =>
                {
                    b.Property<int>("ProposalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("ProposalStatusId");

                    b.ToTable("ProposalStatus");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationItem", b =>
                {
                    b.Property<int>("DeclarationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeclarationItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationRevision", b =>
                {
                    b.Property<int>("DeclarationRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeclarationItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RevisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeclarationRevisionId");

                    b.HasIndex("DeclarationItemId");

                    b.HasIndex("UserId");

                    b.ToTable("DeclarationRevision");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationSignature", b =>
                {
                    b.Property<int>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSigned")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeclarationItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SignatureId");

                    b.HasIndex("DeclarationItemId");

                    b.HasIndex("UserId");

                    b.ToTable("DeclarationSignature");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.FinancialLine", b =>
                {
                    b.Property<int>("FinancialLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccountedValue")
                        .HasColumnType("REAL");

                    b.Property<int>("ActionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdjudicatedValueOriginalCurrency")
                        .HasColumnType("REAL");

                    b.Property<double>("BudgetValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Claim")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExchangeRateToEuro")
                        .HasColumnType("REAL");

                    b.Property<string>("ExpenseAccount")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialLineSubtypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinancialLineTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvestmentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestmentOrder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Invoice")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductionOrder")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProposalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurchaseOrder")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseRequest")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAcceptance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FinancialLineId");

                    b.HasIndex("ActionItemId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FinancialLineSubtypeId");

                    b.HasIndex("FinancialLineTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProposalId");

                    b.ToTable("FinancialLine");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.FinancialLineSubType", b =>
                {
                    b.Property<int>("FinancialLineSubTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("FinancialLineSubTypeId");

                    b.ToTable("FinancialLineSubTypes");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.FinancialLineType", b =>
                {
                    b.Property<int>("FinancialLineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("FinancialLineTypeId");

                    b.ToTable("FinancialLineTypes");
                });

            modelBuilder.Entity("STRACT.Entities.General.AlertType", b =>
                {
                    b.Property<int>("AlertTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("AlertTypeId");

                    b.ToTable("AlertTypes");
                });

            modelBuilder.Entity("STRACT.Entities.General.LineOfProduct", b =>
                {
                    b.Property<int>("LineOfProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("LineOfProductId");

                    b.ToTable("LinesOfProducts");
                });

            modelBuilder.Entity("STRACT.Entities.General.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("STRACT.Entities.General.ToDoTask", b =>
                {
                    b.Property<int>("ToDoTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConcluded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserInTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ToDoTaskId");

                    b.HasIndex("ActionItemId");

                    b.HasIndex("ProjectItemId");

                    b.HasIndex("UserInTeamId");

                    b.ToTable("ToDoTask");
                });

            modelBuilder.Entity("STRACT.Entities.General.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.ActivityGroup", b =>
                {
                    b.Property<int>("ActivityGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityGroupId");

                    b.ToTable("ActivityGroups");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.ActivityInGroup", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityGroupId");

                    b.HasIndex("ActivityId1");

                    b.ToTable("ActivityInGroup");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.FunctionalRole", b =>
                {
                    b.Property<int>("FunctionalRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FunctionalRoleId");

                    b.ToTable("FunctionalRole");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.OrganizationalRole", b =>
                {
                    b.Property<int>("OrganizationalRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganizationalRoleId");

                    b.ToTable("OrganizationalRole");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillGroupId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.SkillGroup", b =>
                {
                    b.Property<int>("SkillGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SkillGroupId");

                    b.ToTable("SkillGroup");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.UserHoliday", b =>
                {
                    b.Property<int>("UserHolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOfHoliday")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserInTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserHolidayId");

                    b.HasIndex("UserInTeamId");

                    b.ToTable("UserHoliday");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.KanbanBoard", b =>
                {
                    b.Property<int>("KanbanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KanbanId");

                    b.HasIndex("ProjectItemId")
                        .IsUnique();

                    b.ToTable("KanbanBoard");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.LocationInKanban", b =>
                {
                    b.Property<int>("LocationInKanbanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationInKanbanId");

                    b.ToTable("LocationInKanbans");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("PriorityId");

                    b.ToTable("Priority");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSprintEnded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KanbanBoardKanbanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SprintId");

                    b.HasIndex("KanbanBoardKanbanId");

                    b.ToTable("Sprint");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskInKanban", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KanbanBoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationInKanbanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SprintId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskItemId");

                    b.HasIndex("KanbanBoardId");

                    b.HasIndex("LocationInKanbanId");

                    b.HasIndex("SprintId");

                    b.HasIndex("SprintId1");

                    b.ToTable("TaskInKanban");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureActivity")
                        .HasColumnType("TEXT");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizationRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationalRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserInTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskItemId");

                    b.HasIndex("AuditId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrganizationalRoleId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TaskTypeId");

                    b.HasIndex("UserInTeamId");

                    b.ToTable("TaskItem");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskType", b =>
                {
                    b.Property<int>("TaskTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskTypeId");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionGroup", b =>
                {
                    b.Property<int>("ActionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionGroupId");

                    b.ToTable("ActionGroups");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionItem", b =>
                {
                    b.Property<int>("ActionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActionPlanRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedIn")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionItemId");

                    b.HasIndex("ActionGroupId");

                    b.HasIndex("ActionPlanRevisionId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectItemId");

                    b.ToTable("ActionItem");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionPlanRevision", b =>
                {
                    b.Property<int>("ActionPlanRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionPlanYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Budget")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RevisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserInTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionPlanRevisionId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("UserInTeamId");

                    b.ToTable("ActionPlanRevision");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.AlertInProject", b =>
                {
                    b.Property<int>("ProjectItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectItemId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectItemId");

                    b.HasIndex("AlertTypeId");

                    b.HasIndex("ProjectItemId1");

                    b.ToTable("AlertInProject");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.LocationsForAction", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationId");

                    b.HasIndex("ActionItemId");

                    b.HasIndex("LocationId1");

                    b.ToTable("LocationsForAction");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ProjectItem", b =>
                {
                    b.Property<int>("ProjectItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConceptsDeveloped")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoordinatorUserInTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailOfProblem")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedResults")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainConclusions")
                        .HasColumnType("TEXT");

                    b.Property<string>("MappedBenefits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectItemId");

                    b.HasIndex("CoordinatorUserInTeamId");

                    b.ToTable("ProjectItem");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ProjectMember", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionOfFunction")
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionalRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserInTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("FunctionalRoleId");

                    b.HasIndex("ProjectItemId");

                    b.HasIndex("UserInTeamId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.TopicInProject", b =>
                {
                    b.Property<int>("ProjectItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectItemId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectItemId");

                    b.HasIndex("ProjectItemId1");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicInProject");
                });

            modelBuilder.Entity("STRACT.Entities.Users.UserInTeam", b =>
                {
                    b.Property<int>("UserInTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationalRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserInTeamId");

                    b.HasIndex("ApplicationUserId1");

                    b.HasIndex("OrganizationalRoleId");

                    b.ToTable("UserInTeam");
                });

            modelBuilder.Entity("STRACT.Identity.General.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("STRACT.Identity.Entities.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<int>("UsernameChangeLimit")
                        .HasColumnType("INTEGER");

                    b.ToTable("ApplicationUser", "Identity");
                });

            modelBuilder.Entity("ActionItemLineOfProduct", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ActionItem", null)
                        .WithMany()
                        .HasForeignKey("ActionItemsActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.General.LineOfProduct", null)
                        .WithMany()
                        .HasForeignKey("LinesOfProductsLineOfProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityFunctionalRole", b =>
                {
                    b.HasOne("STRACT.Entities.HumanResources.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.HumanResources.FunctionalRole", null)
                        .WithMany()
                        .HasForeignKey("FunctionalRolesFunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityOrganizationalRole", b =>
                {
                    b.HasOne("STRACT.Entities.HumanResources.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.HumanResources.OrganizationalRole", null)
                        .WithMany()
                        .HasForeignKey("OrganizationalRolesOrganizationalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivitySkill", b =>
                {
                    b.HasOne("STRACT.Entities.HumanResources.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.HumanResources.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Audit", b =>
                {
                    b.HasOne("STRACT.Entities.Certifications.CertificationLine", "CertificationLine")
                        .WithMany("Audits")
                        .HasForeignKey("CertificationLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.General.Location", "Location")
                        .WithMany("Audits")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "User")
                        .WithMany("Audits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificationLine");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Certificate", b =>
                {
                    b.HasOne("STRACT.Entities.Certifications.CertificationLine", "CertificationLine")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificationLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificationLine");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificateProductLine", b =>
                {
                    b.HasOne("STRACT.Entities.Certifications.Certificate", "Certificate")
                        .WithMany("CertificateProductLines")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.General.LineOfProduct", "LineOfProduct")
                        .WithMany("CertificateProductLines")
                        .HasForeignKey("LineOfProductId");

                    b.Navigation("Certificate");

                    b.Navigation("LineOfProduct");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificationInActionItem", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ActionItem", "ActionItem")
                        .WithMany("CertificationInActionItems")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Certifications.CertificationLine", "Certification")
                        .WithMany("CertificationsInActionItens")
                        .HasForeignKey("CertificationLineId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");

                    b.Navigation("Certification");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificationLine", b =>
                {
                    b.HasOne("STRACT.Entities.Certifications.Entity", "Entity")
                        .WithMany("CertificationLines")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.ContactPerson", b =>
                {
                    b.HasOne("STRACT.Entities.Certifications.Entity", "Entity")
                        .WithMany("Contacts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramLine", b =>
                {
                    b.HasOne("STRACT.Entities.Chronogram.ChronogramRevision", "ChronogramRevision")
                        .WithMany("ChronogramLines")
                        .HasForeignKey("ChronogramRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Chronogram.ChronogramText", "ChronogramText")
                        .WithMany("ChronogramLines")
                        .HasForeignKey("ChronogramTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronogramRevision");

                    b.Navigation("ChronogramText");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramRevision", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ProjectItem", "ProjectItem")
                        .WithMany("Chronograms")
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "Responsible")
                        .WithMany("ChronogramRevisions")
                        .HasForeignKey("ResponsibleUserInTeamId");

                    b.Navigation("ProjectItem");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.CommissionForProject", b =>
                {
                    b.HasOne("STRACT.Entities.CommissionProposals.Commission", "Commission")
                        .WithMany("CommissionForProjects")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commission");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Decision", b =>
                {
                    b.HasOne("STRACT.Entities.CommissionProposals.Commission", "Commission")
                        .WithMany("Decisions")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.CommissionProposals.ProposalStatus", "Status")
                        .WithMany("Decisions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commission");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Proposal", b =>
                {
                    b.HasOne("STRACT.Entities.CommissionProposals.Commission", "Commission")
                        .WithMany("Proposals")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "Responsible")
                        .WithMany("Proposals")
                        .HasForeignKey("ResponsibleUserInTeamId");

                    b.Navigation("Commission");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationItem", b =>
                {
                    b.HasOne("STRACT.Entities.Users.UserInTeam", "User")
                        .WithMany("Declarations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationRevision", b =>
                {
                    b.HasOne("STRACT.Entities.Declaration.DeclarationItem", "DeclarationItem")
                        .WithMany("Revisions")
                        .HasForeignKey("DeclarationItemId");

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "User")
                        .WithMany("DeclarationRevisions")
                        .HasForeignKey("UserId");

                    b.Navigation("DeclarationItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationSignature", b =>
                {
                    b.HasOne("STRACT.Entities.Declaration.DeclarationItem", "Declaration")
                        .WithMany("Signatures")
                        .HasForeignKey("DeclarationItemId");

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "User")
                        .WithMany("DeclarationSignatures")
                        .HasForeignKey("UserId");

                    b.Navigation("Declaration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.FinancialLine", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ActionItem", "ActionItem")
                        .WithMany("FinancialLines")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Financial.Currency", "Currency")
                        .WithMany("FinancialLines")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Financial.FinancialLineSubType", "FinancialLineSubType")
                        .WithMany("FinancialLines")
                        .HasForeignKey("FinancialLineSubtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Financial.FinancialLineType", "FinancialLineType")
                        .WithMany("FinancialLines")
                        .HasForeignKey("FinancialLineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.General.Location", "Location")
                        .WithMany("FinancialLines")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.CommissionProposals.Proposal", "Proposal")
                        .WithMany("FinancialLines")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");

                    b.Navigation("Currency");

                    b.Navigation("FinancialLineSubType");

                    b.Navigation("FinancialLineType");

                    b.Navigation("Location");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("STRACT.Entities.General.ToDoTask", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ActionItem", "ActionItem")
                        .WithMany("ToDoTasks")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Projects.ProjectItem", null)
                        .WithMany("toDoTasks")
                        .HasForeignKey("ProjectItemId");

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "UserInTeam")
                        .WithMany("ToDoTasks")
                        .HasForeignKey("UserInTeamId");

                    b.Navigation("ActionItem");

                    b.Navigation("UserInTeam");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.ActivityInGroup", b =>
                {
                    b.HasOne("STRACT.Entities.HumanResources.ActivityGroup", "ActivityGroup")
                        .WithMany("ActivityInGroups")
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.HumanResources.Activity", "Activity")
                        .WithMany("ActivityInGroups")
                        .HasForeignKey("ActivityId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("ActivityGroup");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.Skill", b =>
                {
                    b.HasOne("STRACT.Entities.HumanResources.SkillGroup", "SkillGroup")
                        .WithMany("Skills")
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillGroup");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.UserHoliday", b =>
                {
                    b.HasOne("STRACT.Entities.Users.UserInTeam", "User")
                        .WithMany("PersonalHolidays")
                        .HasForeignKey("UserInTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.KanbanBoard", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ProjectItem", "ProjectItem")
                        .WithOne("KanbanBoard")
                        .HasForeignKey("STRACT.Entities.Kanban.KanbanBoard", "ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectItem");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.Sprint", b =>
                {
                    b.HasOne("STRACT.Entities.Kanban.KanbanBoard", null)
                        .WithMany("Sprints")
                        .HasForeignKey("KanbanBoardKanbanId");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskInKanban", b =>
                {
                    b.HasOne("STRACT.Entities.Kanban.KanbanBoard", "KanbanBoard")
                        .WithMany("Tasks")
                        .HasForeignKey("KanbanBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Kanban.LocationInKanban", "LocationInKanban")
                        .WithMany("Tasks")
                        .HasForeignKey("LocationInKanbanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Kanban.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId");

                    b.HasOne("STRACT.Entities.Kanban.Sprint", null)
                        .WithMany("Tasks")
                        .HasForeignKey("SprintId1");

                    b.HasOne("STRACT.Entities.Kanban.TaskItem", "TaskItem")
                        .WithOne("TaskInKanban")
                        .HasForeignKey("STRACT.Entities.Kanban.TaskInKanban", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanbanBoard");

                    b.Navigation("LocationInKanban");

                    b.Navigation("Sprint");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskItem", b =>
                {
                    b.HasOne("STRACT.Entities.Certifications.Audit", "Audit")
                        .WithMany("TaskItems")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.HumanResources.Department", "RequestedBy")
                        .WithMany("TaskItems")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.HumanResources.OrganizationalRole", "OrganizationalRole")
                        .WithMany("TaskItems")
                        .HasForeignKey("OrganizationalRoleId");

                    b.HasOne("STRACT.Entities.Kanban.Priority", "Priority")
                        .WithMany("TaskItems")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Kanban.TaskType", "TaskType")
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "UserResponsible")
                        .WithMany("TaskItems")
                        .HasForeignKey("UserInTeamId");

                    b.Navigation("Audit");

                    b.Navigation("OrganizationalRole");

                    b.Navigation("Priority");

                    b.Navigation("RequestedBy");

                    b.Navigation("TaskType");

                    b.Navigation("UserResponsible");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionItem", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ActionGroup", "ActionGroup")
                        .WithMany("ActionItems")
                        .HasForeignKey("ActionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Projects.ActionPlanRevision", "ActionPlanRevision")
                        .WithMany("ActionItems")
                        .HasForeignKey("ActionPlanRevisionId");

                    b.HasOne("STRACT.Entities.HumanResources.Department", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Projects.ProjectItem", "ProjectItem")
                        .WithMany("ActionItems")
                        .HasForeignKey("ProjectItemId");

                    b.Navigation("ActionGroup");

                    b.Navigation("ActionPlanRevision");

                    b.Navigation("ProjectItem");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionPlanRevision", b =>
                {
                    b.HasOne("STRACT.Entities.CommissionProposals.Proposal", "Proposal")
                        .WithOne("ActionPlanRevision")
                        .HasForeignKey("STRACT.Entities.Projects.ActionPlanRevision", "ProposalId");

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "UserInTeam")
                        .WithMany("ActionPlanRevisions")
                        .HasForeignKey("UserInTeamId");

                    b.Navigation("Proposal");

                    b.Navigation("UserInTeam");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.AlertInProject", b =>
                {
                    b.HasOne("STRACT.Entities.General.AlertType", "AlertType")
                        .WithMany("AlertInProjects")
                        .HasForeignKey("AlertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Projects.ProjectItem", "ProjectItem")
                        .WithMany("Alerts")
                        .HasForeignKey("ProjectItemId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertType");

                    b.Navigation("ProjectItem");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.LocationsForAction", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ActionItem", "ActionItem")
                        .WithMany("Locations")
                        .HasForeignKey("ActionItemId");

                    b.HasOne("STRACT.Entities.General.Location", "Location")
                        .WithMany("Actions")
                        .HasForeignKey("LocationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ProjectItem", b =>
                {
                    b.HasOne("STRACT.Entities.Users.UserInTeam", "Coordinator")
                        .WithMany("ProjectsCoordinated")
                        .HasForeignKey("CoordinatorUserInTeamId");

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ProjectMember", b =>
                {
                    b.HasOne("STRACT.Entities.HumanResources.FunctionalRole", "FunctionalRole")
                        .WithMany("Projects")
                        .HasForeignKey("FunctionalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Projects.ProjectItem", "ProjectItem")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.Users.UserInTeam", "User")
                        .WithMany("ProjectsInTeam")
                        .HasForeignKey("UserInTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalRole");

                    b.Navigation("ProjectItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.TopicInProject", b =>
                {
                    b.HasOne("STRACT.Entities.Projects.ProjectItem", "ProjectItem")
                        .WithMany("Topics")
                        .HasForeignKey("ProjectItemId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STRACT.Entities.General.Topic", "Topic")
                        .WithMany("TopicInProjects")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectItem");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("STRACT.Entities.Users.UserInTeam", b =>
                {
                    b.HasOne("STRACT.Identity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId1");

                    b.HasOne("STRACT.Entities.HumanResources.OrganizationalRole", "OrganizationalRole")
                        .WithMany()
                        .HasForeignKey("OrganizationalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("OrganizationalRole");
                });

            modelBuilder.Entity("STRACT.Identity.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("STRACT.Identity.Entities.ApplicationUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Audit", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Certificate", b =>
                {
                    b.Navigation("CertificateProductLines");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.CertificationLine", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Certificates");

                    b.Navigation("CertificationsInActionItens");
                });

            modelBuilder.Entity("STRACT.Entities.Certifications.Entity", b =>
                {
                    b.Navigation("CertificationLines");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramRevision", b =>
                {
                    b.Navigation("ChronogramLines");
                });

            modelBuilder.Entity("STRACT.Entities.Chronogram.ChronogramText", b =>
                {
                    b.Navigation("ChronogramLines");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Commission", b =>
                {
                    b.Navigation("CommissionForProjects");

                    b.Navigation("Decisions");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.Proposal", b =>
                {
                    b.Navigation("ActionPlanRevision");

                    b.Navigation("FinancialLines");
                });

            modelBuilder.Entity("STRACT.Entities.CommissionProposals.ProposalStatus", b =>
                {
                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("STRACT.Entities.Declaration.DeclarationItem", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.Currency", b =>
                {
                    b.Navigation("FinancialLines");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.FinancialLineSubType", b =>
                {
                    b.Navigation("FinancialLines");
                });

            modelBuilder.Entity("STRACT.Entities.Financial.FinancialLineType", b =>
                {
                    b.Navigation("FinancialLines");
                });

            modelBuilder.Entity("STRACT.Entities.General.AlertType", b =>
                {
                    b.Navigation("AlertInProjects");
                });

            modelBuilder.Entity("STRACT.Entities.General.LineOfProduct", b =>
                {
                    b.Navigation("CertificateProductLines");
                });

            modelBuilder.Entity("STRACT.Entities.General.Location", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Audits");

                    b.Navigation("FinancialLines");
                });

            modelBuilder.Entity("STRACT.Entities.General.Topic", b =>
                {
                    b.Navigation("TopicInProjects");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.Activity", b =>
                {
                    b.Navigation("ActivityInGroups");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.ActivityGroup", b =>
                {
                    b.Navigation("ActivityInGroups");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.Department", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.FunctionalRole", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.OrganizationalRole", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("STRACT.Entities.HumanResources.SkillGroup", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.KanbanBoard", b =>
                {
                    b.Navigation("Sprints");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.LocationInKanban", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.Priority", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.Sprint", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskItem", b =>
                {
                    b.Navigation("TaskInKanban");
                });

            modelBuilder.Entity("STRACT.Entities.Kanban.TaskType", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionGroup", b =>
                {
                    b.Navigation("ActionItems");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionItem", b =>
                {
                    b.Navigation("CertificationInActionItems");

                    b.Navigation("FinancialLines");

                    b.Navigation("Locations");

                    b.Navigation("ToDoTasks");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ActionPlanRevision", b =>
                {
                    b.Navigation("ActionItems");
                });

            modelBuilder.Entity("STRACT.Entities.Projects.ProjectItem", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Alerts");

                    b.Navigation("Chronograms");

                    b.Navigation("KanbanBoard");

                    b.Navigation("ProjectMembers");

                    b.Navigation("toDoTasks");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("STRACT.Entities.Users.UserInTeam", b =>
                {
                    b.Navigation("ActionPlanRevisions");

                    b.Navigation("Audits");

                    b.Navigation("ChronogramRevisions");

                    b.Navigation("DeclarationRevisions");

                    b.Navigation("Declarations");

                    b.Navigation("DeclarationSignatures");

                    b.Navigation("PersonalHolidays");

                    b.Navigation("ProjectsCoordinated");

                    b.Navigation("ProjectsInTeam");

                    b.Navigation("Proposals");

                    b.Navigation("TaskItems");

                    b.Navigation("ToDoTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
